[project]
name = "var2stat"
version = "0.1.0"
description = "Convert variable fonts to static font instances"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.1",
    "fonttools>=4.61.1",
    "jsonschema>=4.25.1",
]
